### ISSUE TITLE
Missing JavaFX Dependency

### ISSUE THREAD

**Issue by josh-127** [andy98725/Base-Wars-3#3]
When starting the game, it crashes with this stack trace:
```
C:\Base-Wars-3>java -jar -Xmx512m Base_Wars.jar
Exception in thread "Loading Thread" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at textures.audio.AudioPlayer.<init>(AudioPlayer.java:28)
        at main.Game$1.run(Game.java:115)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
java.lang.NullPointerException
        at main.Game.openMainMenu(Game.java:156)
        at textures.IntroCard.end(IntroCard.java:148)
        at textures.IntroCard.logic(IntroCard.java:127)
        at main.Game.logic(Game.java:228)
        at main.Application.mainCycle(Application.java:37)
        at main.Application.access$0(Application.java:25)
        at main.Application$1$1.run(Application.java:140)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Here are the packages I installed through [Chocolatey](https://chocolatey.org/):
```
C:\> choco list --local-only
jdk11 11.0.2
jdk8 8.0.201
maven 3.6.0
```

**Comment by josh-127** [comment]
I figured it out. JavaFX is no longer part of Java 11, so I had to use Java 8 with this temporary fix:
`"C:\Program Files\Java\jdk1.8.0_201\bin\java.exe" -jar -Xmx512m Base_Wars.jar`

Remember that Java 8 is no longer supported. I suggest upgrading your project to Java 11.

**Comment by andy98725** [comment]
I Added JavaFX as an external library during compilation.
